CREATE DATABASE LIGAPRO_DB
GO

USE LIGAPRO_DB
GO

CREATE TABLE DEPORTES(
	IdDeporte INT IDENTITY(1,1),
	Nombre INT NOT NULL,
	CantidadJugadores INT NOT NULL,
	CONSTRAINT PK_DEPORTES PRIMARY KEY (IdDeporte)
)
GO
